// Generated by CoffeeScript 1.10.0
(function() {
  var autopre, coffee, gulp, jade, sass;

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  jade = require('gulp-jade');

  sass = require('gulp-sass');

  autopre = require('gulp-autoprefixer');

  gulp.task('coffee', function() {
    gulp.src('./src/coffee/*.coffee').pipe(coffee()).pipe(gulp.dest('./js'));
  });

  gulp.task('sass', function() {
    gulp.src('./src/scss/*.scss').pipe(sass()).pipe(gulp.dest('./css'));
  });

  gulp.task('autoprefix', function() {
    gulp.src('./css/*.css').pipe(autopre({
      browsers: ['last 3 versions'],
      cascade: false
    })).pipe(gulp.dest('./css'));
  });

  gulp.task('watch', function() {
    gulp.watch('./src/coffee/*.coffee', ['coffee']);
    gulp.watch('./src/scss/*.scss', ['sass']);
    gulp.watch('./css/*.css', ['autoprefix']);
  });

  gulp.task('default', ['watch', 'coffee', 'sass', 'autoprefix']);

}).call(this);
